# Generated by Django 2.2.4 on 2019-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default=12, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_date',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('cc', 'Credit Card'), ('dc', 'Debit Card')], max_length=256),
        ),
    ]
