# Generated by Django 2.2.4 on 2019-08-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190805_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Artist'),
        ),
    ]
