# Generated by Django 2.2.4 on 2019-08-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190805_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
