# Generated by Django 2.2.4 on 2019-08-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payment_cvv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expiration_date',
            new_name='expiration_year',
        ),
    ]
