# Generated by Django 2.2.4 on 2019-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190812_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='soldStatus',
            field=models.BooleanField(default=False),
        ),
    ]
