# Generated by Django 2.2.4 on 2019-08-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190815_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='painting_image'),
        ),
    ]
